name: example
description: A practical demonstration of using repository_kit in a Flutter application.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  repository_kit:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
